
// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Fluxo de autocompletar código com IA.
 *
 * - aiCodeCompletion - Uma função que sugere trechos de código conforme você digita.
 * - AiCodeCompletionInput - O tipo de entrada para a função aiCodeCompletion.
 * - AiCodeCompletionOutput - O tipo de retorno para a função aiCodeCompletion.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AiCodeCompletionInputSchema = z.object({
  codePrefix: z
    .string()
    .describe('O prefixo de código que o usuário já digitou.'),
  language: z.string().describe('A linguagem de programação do código.'),
});
export type AiCodeCompletionInput = z.infer<typeof AiCodeCompletionInputSchema>;

const AiCodeCompletionOutputSchema = z.object({
  suggestion: z.string().describe('O trecho de código sugerido.'),
});
export type AiCodeCompletionOutput = z.infer<typeof AiCodeCompletionOutputSchema>;

export async function aiCodeCompletion(input: AiCodeCompletionInput): Promise<AiCodeCompletionOutput> {
  return aiCodeCompletionFlow(input);
}

const prompt = ai.definePrompt({
  name: 'aiCodeCompletionPrompt',
  input: {schema: AiCodeCompletionInputSchema},
  output: {schema: AiCodeCompletionOutputSchema},
  prompt: `Você é uma ferramenta de autocompletar código com IA. Você sugerirá a(s) próxima(s) linha(s) de código com base no prefixo de código e na linguagem de programação fornecidos.

Linguagem: {{{language}}}
Prefixo do Código:
{{{codePrefix}}}

Sugestão:`,
});

const aiCodeCompletionFlow = ai.defineFlow(
  {
    name: 'aiCodeCompletionFlow',
    inputSchema: AiCodeCompletionInputSchema,
    outputSchema: AiCodeCompletionOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
